import { CommandRegistry } from "../../commands/command.js";
import { sayCommand } from "./commands/say.js";
import { stealCommand } from "./commands/steal.js";
import { nicknameCommand } from "./commands/nickname.js";
import { purgeCommand } from "./commands/purge.js";
import { purgebotsCommand } from "./commands/purgebots.js";
import { roleiconCommand } from "./commands/roleicon.js";
import { roleCommand } from "./commands/role.js";
import { roleallCommand } from "./commands/roleall.js";
import { banCommand } from "./commands/ban.js";
import { unbanCommand } from "./commands/unban.js";
import { unbanallCommand } from "./commands/unbanall.js";
import { kickCommand } from "./commands/kick.js";
import { muteCommand } from "./commands/mute.js";
import { unmuteCommand } from "./commands/unmute.js";
import { hideCommand } from "./commands/hide.js";
import { hideallCommand } from "./commands/hideall.js";
import { unhideCommand } from "./commands/unhide.js";
import { unhideallCommand } from "./commands/unhideall.js";
import { lockCommand } from "./commands/lock.js";
import { lockallCommand } from "./commands/lockall.js";
import { unlockCommand } from "./commands/unlock.js";
import { unlockallCommand } from "./commands/unlockall.js";
import { slowmodeCommand } from "./commands/slowmode.js";

export function registerModeration() {
  CommandRegistry.register(sayCommand);
  CommandRegistry.register(stealCommand);
  CommandRegistry.register(nicknameCommand);
  CommandRegistry.register(purgeCommand);
  CommandRegistry.register(purgebotsCommand);
  CommandRegistry.register(roleiconCommand);
  CommandRegistry.register(roleCommand);
  CommandRegistry.register(roleallCommand);
  CommandRegistry.register(banCommand);
  CommandRegistry.register(unbanCommand);
  CommandRegistry.register(unbanallCommand);
  CommandRegistry.register(kickCommand);
  CommandRegistry.register(muteCommand);
  CommandRegistry.register(unmuteCommand);
  CommandRegistry.register(hideCommand);
  CommandRegistry.register(hideallCommand);
  CommandRegistry.register(unhideCommand);
  CommandRegistry.register(unhideallCommand);
  CommandRegistry.register(lockCommand);
  CommandRegistry.register(lockallCommand);
  CommandRegistry.register(unlockCommand);
  CommandRegistry.register(unlockallCommand);
  CommandRegistry.register(slowmodeCommand);
}
